import mclarenEiffelImage from "./assets/mclaren-eiffel.png";
import mercedesAmgImage from "./assets/mercedes-amg.png";

export type Car = {
  id: string;
  make: string;
  model: string;
  transmission: "Automatic" | "Manual";
  generation: string;
  year: number;
  image: string;
  rating: number;
  ratings: number;
  driven: number;
  owners: number;
  tags: string[];
};

const audiModels = [
  { id: "rs3-8y", model: "RS 3", generation: "8Y", year: 2023, tags: ["Turbo", "Quattro", "Hot hatch", "Five-cylinder"] },
  { id: "rs4-b9", model: "RS 4", generation: "B9", year: 2021, tags: ["Turbo", "Quattro", "Avant", "V6"] },
  { id: "rs5-b9", model: "RS 5", generation: "B9", year: 2022, tags: ["Turbo", "Quattro", "Coupe", "V6"] },
  { id: "rs6-c8", model: "RS 6", generation: "C8", year: 2023, tags: ["V8", "Quattro", "Avant", "Super wagon"] },
  { id: "rs7-c8", model: "RS 7", generation: "C8", year: 2022, tags: ["V8", "Quattro", "Sportback", "Grand tourer"] },
  { id: "rs-tt-8s", model: "RS TT", generation: "8S", year: 2020, tags: ["Turbo", "Quattro", "Coupe", "Five-cylinder"] },
  { id: "rsq3-f3", model: "RS Q3", generation: "F3", year: 2023, tags: ["Turbo", "Quattro", "SUV", "Five-cylinder"] },
  { id: "rsq8-4m", model: "RS Q8", generation: "4M", year: 2022, tags: ["V8", "Quattro", "SUV", "Performance"] },
  { id: "s1-8x", model: "S 1", generation: "8X", year: 2017, tags: ["Turbo", "Quattro", "Hot hatch", "Compact"] },
  { id: "s3-8y", model: "S 3", generation: "8Y", year: 2023, tags: ["Turbo", "Quattro", "Sportback", "Daily"] },
  { id: "s4-b9", model: "S 4", generation: "B9", year: 2021, tags: ["Turbo", "Quattro", "Sedan", "V6"] },
  { id: "s5-b9", model: "S 5", generation: "B9", year: 2022, tags: ["Turbo", "Quattro", "Coupe", "V6"] },
  { id: "s6-c8", model: "S 6", generation: "C8", year: 2022, tags: ["Turbo", "Quattro", "Sedan", "V6"] },
  { id: "s7-c8", model: "S 7", generation: "C8", year: 2023, tags: ["Turbo", "Quattro", "Sportback", "V6"] },
  { id: "s8-d5", model: "S 8", generation: "D5", year: 2022, tags: ["V8", "Quattro", "Luxury", "Sedan"] },
  { id: "sq5-fy", model: "S Q5", generation: "FY", year: 2023, tags: ["Turbo", "Quattro", "SUV", "V6"] },
  { id: "s-tt-8s", model: "S TT", generation: "8S", year: 2020, tags: ["Turbo", "Quattro", "Coupe", "Roadster"] },
];

const ferrariModels: Array<Pick<Car, "id" | "model" | "generation" | "year" | "transmission" | "tags">> = [
  { id: "f12-berlinetta", model: "F12", generation: "Berlinetta", year: 2015, transmission: "Automatic", tags: ["V12", "Grand tourer", "RWD", "Naturally aspirated"] },
  { id: "599-gtb", model: "599", generation: "GTB Fiorano", year: 2008, transmission: "Automatic", tags: ["V12", "Grand tourer", "RWD", "Naturally aspirated"] },
  { id: "f430", model: "F430", generation: "F131", year: 2007, transmission: "Manual", tags: ["V8", "Mid-engine", "RWD", "Analog"] },
  { id: "812-superfast", model: "812", generation: "Superfast", year: 2020, transmission: "Automatic", tags: ["V12", "Grand tourer", "RWD", "Naturally aspirated"] },
  { id: "488-gtb", model: "488", generation: "GTB", year: 2017, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Mid-engine", "RWD"] },
  { id: "296-gtb", model: "296", generation: "GTB", year: 2023, transmission: "Automatic", tags: ["V6", "Hybrid", "Mid-engine", "RWD"] },
  { id: "360-modena", model: "360", generation: "Modena", year: 2001, transmission: "Manual", tags: ["V8", "Mid-engine", "RWD", "Analog"] },
  { id: "roma", model: "Roma", generation: "F169", year: 2022, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Grand tourer", "RWD"] },
  { id: "california-t", model: "California", generation: "T", year: 2016, transmission: "Automatic", tags: ["V8", "Convertible", "Grand tourer", "RWD"] },
  { id: "daytona-sp3", model: "Daytona", generation: "SP3", year: 2023, transmission: "Automatic", tags: ["V12", "Icona", "Mid-engine", "Limited"] },
  { id: "f40", model: "F40", generation: "Type F120", year: 1990, transmission: "Manual", tags: ["V8", "Twin-turbo", "Manual", "Icon"] },
  { id: "f50", model: "F50", generation: "Type F130", year: 1997, transmission: "Manual", tags: ["V12", "Manual", "Mid-engine", "Icon"] },
];

const astonMartinModels: Array<Pick<Car, "id" | "model" | "generation" | "year" | "transmission" | "tags">> = [
  { id: "aston-v8-vantage", model: "V8 Vantage", generation: "AM6", year: 2016, transmission: "Manual", tags: ["V8", "Grand tourer", "RWD", "British"] },
  { id: "aston-v12-vantage", model: "V12 Vantage", generation: "AM6", year: 2017, transmission: "Manual", tags: ["V12", "Grand tourer", "RWD", "British"] },
  { id: "aston-vanquish", model: "Vanquish", generation: "Second generation", year: 2016, transmission: "Automatic", tags: ["V12", "Grand tourer", "RWD", "British"] },
  { id: "aston-vanquish-s", model: "Vanquish S", generation: "Second generation", year: 2018, transmission: "Automatic", tags: ["V12", "Grand tourer", "RWD", "Performance"] },
  { id: "aston-rapide", model: "Rapide", generation: "S", year: 2016, transmission: "Automatic", tags: ["V12", "Four-door", "Luxury", "Grand tourer"] },
  { id: "aston-db11", model: "DB 11", generation: "AM5", year: 2020, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Grand tourer", "Luxury"] },
  { id: "aston-db12", model: "DB 12", generation: "AM8", year: 2024, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Super tourer", "Luxury"] },
  { id: "aston-db9", model: "DB 9", generation: "AM5", year: 2015, transmission: "Automatic", tags: ["V12", "Grand tourer", "RWD", "Luxury"] },
  { id: "aston-db6", model: "DB 6", generation: "Mark 2", year: 1970, transmission: "Manual", tags: ["Straight-6", "Classic", "Grand tourer", "British"] },
  { id: "aston-db7", model: "DB 7", generation: "Vantage", year: 2002, transmission: "Manual", tags: ["V12", "Classic", "Grand tourer", "British"] },
  { id: "aston-dbs", model: "DBS", generation: "Superleggera", year: 2021, transmission: "Automatic", tags: ["V12", "Twin-turbo", "Grand tourer", "Performance"] },
];

const lamborghiniModels: Array<Pick<Car, "id" | "model" | "generation" | "year" | "transmission" | "tags">> = [
  { id: "lamborghini-aventador", model: "Aventador", generation: "LP 700-4", year: 2016, transmission: "Automatic", tags: ["V12", "AWD", "Mid-engine", "Supercar"] },
  { id: "lamborghini-huracan", model: "Huracan", generation: "LP 610-4", year: 2018, transmission: "Automatic", tags: ["V10", "AWD", "Mid-engine", "Supercar"] },
  { id: "lamborghini-gallardo", model: "Gallardo", generation: "LP 560-4", year: 2010, transmission: "Manual", tags: ["V10", "AWD", "Mid-engine", "Analog"] },
  { id: "lamborghini-murcielago", model: "Murcielago", generation: "LP 640", year: 2008, transmission: "Manual", tags: ["V12", "AWD", "Mid-engine", "Icon"] },
  { id: "lamborghini-urus", model: "Urus", generation: "First generation", year: 2022, transmission: "Automatic", tags: ["V8", "Twin-turbo", "AWD", "Performance SUV"] },
];

const porscheModels: Array<Pick<Car, "id" | "model" | "generation" | "year" | "transmission" | "tags">> = [
  { id: "porsche-911-carrera-4s", model: "911 Carrera 4S", generation: "992", year: 2022, transmission: "Automatic", tags: ["Flat-6", "AWD", "Sports car", "Daily"] },
  { id: "porsche-911-targa-4s", model: "911 Targa 4S", generation: "992", year: 2022, transmission: "Automatic", tags: ["Flat-6", "AWD", "Targa", "Grand tourer"] },
  { id: "porsche-911-targa-s", model: "911 Targa S", generation: "997.2", year: 2011, transmission: "Manual", tags: ["Flat-6", "RWD", "Targa", "Driver"] },
  { id: "porsche-911-carrera-gts", model: "911 Carrera GTS", generation: "992", year: 2023, transmission: "Automatic", tags: ["Flat-6", "Turbo", "RWD", "Performance"] },
  { id: "porsche-911-gt2", model: "911 GT2", generation: "997", year: 2009, transmission: "Manual", tags: ["Flat-6", "Twin-turbo", "RWD", "Analog"] },
  { id: "porsche-911-gt2-rs", model: "911 GT2 RS", generation: "991.2", year: 2018, transmission: "Automatic", tags: ["Flat-6", "Twin-turbo", "RWD", "Track"] },
  { id: "porsche-911-gt3", model: "911 GT3", generation: "992", year: 2022, transmission: "Automatic", tags: ["Flat-6", "Naturally aspirated", "RWD", "Track"] },
  { id: "porsche-911-gt3-rs", model: "911 GT3 RS", generation: "992", year: 2023, transmission: "Automatic", tags: ["Flat-6", "Naturally aspirated", "RWD", "Track"] },
  { id: "porsche-911-turbo", model: "911 Turbo", generation: "992", year: 2022, transmission: "Automatic", tags: ["Flat-6", "Twin-turbo", "AWD", "Supercar"] },
  { id: "porsche-911-turbo-s", model: "911 Turbo S", generation: "992", year: 2022, transmission: "Automatic", tags: ["Flat-6", "Twin-turbo", "AWD", "Supercar"] },
  { id: "porsche-boxster", model: "Boxster", generation: "981 GTS", year: 2016, transmission: "Manual", tags: ["Flat-6", "Roadster", "Mid-engine", "Driver"] },
  { id: "porsche-cayman", model: "Cayman", generation: "981 S", year: 2015, transmission: "Manual", tags: ["Flat-6", "Coupe", "Mid-engine", "Driver"] },
  { id: "porsche-cayman-gt4", model: "Cayman GT4", generation: "718", year: 2021, transmission: "Manual", tags: ["Flat-6", "Naturally aspirated", "Mid-engine", "Track"] },
  { id: "porsche-cayenne", model: "Cayenne", generation: "E3", year: 2022, transmission: "Automatic", tags: ["V8", "Turbo", "AWD", "Performance SUV"] },
  { id: "porsche-macan", model: "Macan", generation: "95B", year: 2022, transmission: "Automatic", tags: ["V6", "Turbo", "AWD", "Sport SUV"] },
];

const mclarenModels: Array<Pick<Car, "id" | "model" | "generation" | "year" | "transmission" | "tags">> = [
  { id: "mclaren-720s", model: "720S", generation: "Super Series", year: 2021, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Mid-engine", "Supercar"] },
  { id: "mclaren-mp4-12c", model: "MP4-12C", generation: "12C", year: 2013, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Mid-engine", "Supercar"] },
  { id: "mclaren-570s", model: "570S", generation: "Sports Series", year: 2018, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Mid-engine", "Sports car"] },
  { id: "mclaren-600lt", model: "600LT", generation: "Sports Series", year: 2019, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Longtail", "Track"] },
  { id: "mclaren-675lt", model: "675LT", generation: "Super Series", year: 2016, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Longtail", "Track"] },
  { id: "mclaren-540c", model: "540C", generation: "Sports Series", year: 2017, transmission: "Automatic", tags: ["V8", "Twin-turbo", "Mid-engine", "Sports car"] },
];

export const cars: Car[] = [
  {
    id: "r8-v8",
    make: "Audi",
    model: "R8",
    generation: "Type 42",
    year: 2012,
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80",
    rating: 9.1,
    ratings: 842,
    driven: 1190,
    owners: 284,
    transmission: "Manual",
    tags: ["V8", "Manual", "Analog", "Weekend"],
  },
  {
    id: "997-carrera-s",
    make: "Porsche",
    model: "911 Carrera S",
    generation: "997.2",
    year: 2010,
    image: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80",
    rating: 9.3,
    ratings: 1240,
    driven: 1860,
    owners: 412,
    transmission: "Manual",
    tags: ["Flat-6", "Manual", "Classic", "Driver"],
  },
  {
    id: "m3-e46",
    make: "BMW",
    model: "M3",
    generation: "E46",
    year: 2004,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    rating: 9.2,
    ratings: 2184,
    driven: 3020,
    owners: 690,
    transmission: "Manual",
    tags: ["Straight-6", "Manual", "Icon", "Driver"],
  },
  {
    id: "a110",
    make: "Alpine",
    model: "A110",
    generation: "Pure",
    year: 2022,
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
    rating: 8.8,
    ratings: 524,
    driven: 810,
    owners: 156,
    transmission: "Automatic",
    tags: ["Lightweight", "Turbo", "French", "Fun"],
  },
  {
    id: "alpine-a110s",
    make: "Alpine",
    model: "A110S",
    generation: "A110",
    year: 2023,
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
    rating: 9.0,
    ratings: 318,
    driven: 472,
    owners: 96,
    transmission: "Automatic",
    tags: ["Lightweight", "Turbo", "Sport", "French"],
  },
  {
    id: "alpine-a110r",
    make: "Alpine",
    model: "A110R",
    generation: "A110",
    year: 2024,
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
    rating: 9.2,
    ratings: 184,
    driven: 251,
    owners: 43,
    transmission: "Automatic",
    tags: ["Lightweight", "Carbon", "Track", "French"],
  },
  {
    id: "miata-na",
    make: "Mazda",
    model: "MX-5 Miata",
    generation: "NA",
    year: 1993,
    image: "https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1200&q=80",
    rating: 8.9,
    ratings: 1872,
    driven: 2680,
    owners: 721,
    transmission: "Manual",
    tags: ["Roadster", "Manual", "Lightweight", "Pop-ups"],
  },
  {
    id: "m2-f87",
    make: "BMW",
    model: "M2",
    generation: "F87",
    year: 2018,
    image: "https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1200&q=80",
    rating: 9.0,
    ratings: 1148,
    driven: 1735,
    owners: 394,
    transmission: "Manual",
    tags: ["Turbo", "Rear-wheel drive", "Coupe", "Driver"],
  },
  {
    id: "bmw-m1-e26",
    make: "BMW",
    model: "M1",
    generation: "E26",
    year: 1981,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    rating: 9.4,
    ratings: 642,
    driven: 318,
    owners: 74,
    transmission: "Manual",
    tags: ["Mid-engine", "Classic", "Manual", "Icon"],
  },
  {
    id: "bmw-m4-g82",
    make: "BMW",
    model: "M4",
    generation: "G82",
    year: 2024,
    image: "https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1200&q=80",
    rating: 8.9,
    ratings: 1356,
    driven: 2041,
    owners: 486,
    transmission: "Automatic",
    tags: ["Turbo", "Coupe", "Performance", "Rear-wheel drive"],
  },
  {
    id: "bmw-m5-f90",
    make: "BMW",
    model: "M5",
    generation: "F90",
    year: 2022,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    rating: 9.1,
    ratings: 1684,
    driven: 2460,
    owners: 538,
    transmission: "Automatic",
    tags: ["V8", "Turbo", "Super sedan", "All-wheel drive"],
  },
  {
    id: "bmw-z1",
    make: "BMW",
    model: "Z1",
    generation: "E30 Z",
    year: 1991,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    rating: 8.8,
    ratings: 274,
    driven: 192,
    owners: 61,
    transmission: "Manual",
    tags: ["Roadster", "Classic", "Manual", "Rare"],
  },
  {
    id: "bmw-z3",
    make: "BMW",
    model: "Z3",
    generation: "E36/7",
    year: 2001,
    image: "https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1200&q=80",
    rating: 8.5,
    ratings: 712,
    driven: 1048,
    owners: 326,
    transmission: "Manual",
    tags: ["Roadster", "Manual", "Rear-wheel drive", "Classic"],
  },
  {
    id: "bmw-z4-g29",
    make: "BMW",
    model: "Z4",
    generation: "G29",
    year: 2024,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    rating: 8.7,
    ratings: 824,
    driven: 1268,
    owners: 291,
    transmission: "Automatic",
    tags: ["Roadster", "Turbo", "Rear-wheel drive", "Convertible"],
  },
  {
    id: "c63-w204",
    make: "Mercedes",
    model: "C63",
    generation: "W204",
    year: 2012,
    image: mercedesAmgImage,
    rating: 8.9,
    ratings: 768,
    driven: 1050,
    owners: 245,
    transmission: "Automatic",
    tags: ["V8", "AMG", "Sedan", "Naturally aspirated"],
  },
  {
    id: "mercedes-e63-w213",
    make: "Mercedes",
    model: "E63",
    generation: "W213",
    year: 2022,
    image: mercedesAmgImage,
    rating: 9.1,
    ratings: 1642,
    driven: 2418,
    owners: 584,
    transmission: "Automatic",
    tags: ["V8", "AMG", "Super sedan", "All-wheel drive"],
  },
  {
    id: "mercedes-s63-w223",
    make: "Mercedes",
    model: "S63",
    generation: "W223",
    year: 2024,
    image: mercedesAmgImage,
    rating: 8.9,
    ratings: 916,
    driven: 1282,
    owners: 286,
    transmission: "Automatic",
    tags: ["V8", "AMG", "Luxury", "Performance"],
  },
  {
    id: "mercedes-slr-mclaren",
    make: "Mercedes",
    model: "SLR",
    generation: "C199",
    year: 2009,
    image: mercedesAmgImage,
    rating: 9.4,
    ratings: 874,
    driven: 436,
    owners: 82,
    transmission: "Automatic",
    tags: ["Supercharged V8", "Grand tourer", "McLaren", "Icon"],
  },
  {
    id: "mercedes-sls-amg",
    make: "Mercedes",
    model: "SLS",
    generation: "C197",
    year: 2014,
    image: mercedesAmgImage,
    rating: 9.3,
    ratings: 1126,
    driven: 682,
    owners: 134,
    transmission: "Automatic",
    tags: ["V8", "Gullwing", "Supercar", "AMG"],
  },
  {
    id: "mercedes-amg-gt",
    make: "Mercedes",
    model: "AMG GT",
    generation: "C192",
    year: 2024,
    image: mercedesAmgImage,
    rating: 9.0,
    ratings: 1378,
    driven: 1944,
    owners: 438,
    transmission: "Automatic",
    tags: ["V8", "AMG", "Grand tourer", "Performance"],
  },
  {
    id: "mercedes-g63-w463",
    make: "Mercedes",
    model: "G63",
    generation: "W463",
    year: 2024,
    image: mercedesAmgImage,
    rating: 8.7,
    ratings: 2084,
    driven: 3162,
    owners: 862,
    transmission: "Automatic",
    tags: ["V8", "AMG", "4x4", "Luxury"],
  },
  {
    id: "mercedes-cls63-c218",
    make: "Mercedes",
    model: "CLS63",
    generation: "C218",
    year: 2017,
    image: mercedesAmgImage,
    rating: 8.9,
    ratings: 1034,
    driven: 1586,
    owners: 402,
    transmission: "Automatic",
    tags: ["V8", "AMG", "Four-door coupe", "Luxury"],
  },
  {
    id: "bugatti-veyron",
    make: "Bugatti",
    model: "Veyron",
    generation: "16.4",
    year: 2015,
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=1200&q=80",
    rating: 9.3,
    ratings: 986,
    driven: 412,
    owners: 72,
    transmission: "Automatic",
    tags: ["W16", "Quad-turbo", "All-wheel drive", "Hypercar"],
  },
  {
    id: "bugatti-chiron",
    make: "Bugatti",
    model: "Chiron",
    generation: "Chiron",
    year: 2022,
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=1200&q=80",
    rating: 9.5,
    ratings: 1218,
    driven: 376,
    owners: 64,
    transmission: "Automatic",
    tags: ["W16", "Quad-turbo", "All-wheel drive", "Hypercar"],
  },
  {
    id: "chevrolet-corvette-c8",
    make: "Chevrolet",
    model: "Corvette",
    generation: "C8",
    year: 2024,
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
    rating: 9.1,
    ratings: 2146,
    driven: 3268,
    owners: 842,
    transmission: "Automatic",
    tags: ["V8", "Mid-engine", "Sports car", "American"],
  },
  {
    id: "chevrolet-camaro-sixth-gen",
    make: "Chevrolet",
    model: "Camaro",
    generation: "Sixth generation",
    year: 2023,
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
    rating: 8.7,
    ratings: 1852,
    driven: 2894,
    owners: 916,
    transmission: "Manual",
    tags: ["V8", "Muscle car", "Manual", "American"],
  },
  {
    id: "elise-s3",
    make: "Lotus",
    model: "Elise",
    generation: "S3",
    year: 2017,
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    rating: 9.2,
    ratings: 642,
    driven: 930,
    owners: 188,
    transmission: "Manual",
    tags: ["Lightweight", "Mid-engine", "Manual", "Analog"],
  },
  {
    id: "lotus-exige-s3",
    make: "Lotus",
    model: "Exige",
    generation: "S3",
    year: 2021,
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    rating: 9.3,
    ratings: 718,
    driven: 864,
    owners: 172,
    transmission: "Manual",
    tags: ["Supercharged", "Lightweight", "Track", "Manual"],
  },
  {
    id: "lotus-emira",
    make: "Lotus",
    model: "Emira",
    generation: "Type 131",
    year: 2024,
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    rating: 9.0,
    ratings: 936,
    driven: 1284,
    owners: 314,
    transmission: "Manual",
    tags: ["Mid-engine", "Sports car", "Manual", "Driver"],
  },
  {
    id: "lotus-evora",
    make: "Lotus",
    model: "Evora",
    generation: "Type 122",
    year: 2020,
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    rating: 8.9,
    ratings: 684,
    driven: 972,
    owners: 238,
    transmission: "Manual",
    tags: ["Mid-engine", "Grand tourer", "Manual", "Lightweight"],
  },
  {
    id: "maserati-granturismo",
    make: "Maserati",
    model: "Granturismo",
    generation: "M189",
    year: 2024,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    rating: 8.8,
    ratings: 926,
    driven: 1382,
    owners: 348,
    transmission: "Automatic",
    tags: ["Grand tourer", "Italian", "Twin-turbo", "Coupe"],
  },
  {
    id: "maserati-quattroporte",
    make: "Maserati",
    model: "Quattroporte",
    generation: "M156",
    year: 2021,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    rating: 8.4,
    ratings: 812,
    driven: 1264,
    owners: 371,
    transmission: "Automatic",
    tags: ["Luxury", "Sedan", "Italian", "Twin-turbo"],
  },
  {
    id: "maserati-3200gt",
    make: "Maserati",
    model: "3200GT",
    generation: "Tipo 338",
    year: 2001,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    rating: 8.6,
    ratings: 468,
    driven: 624,
    owners: 196,
    transmission: "Manual",
    tags: ["V8", "Twin-turbo", "Grand tourer", "Classic"],
  },
  {
    id: "maserati-mc20",
    make: "Maserati",
    model: "MC20",
    generation: "M240",
    year: 2024,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    rating: 9.2,
    ratings: 734,
    driven: 698,
    owners: 128,
    transmission: "Automatic",
    tags: ["Mid-engine", "Supercar", "Twin-turbo", "Italian"],
  },
  {
    id: "mini-cooper-s-f56",
    make: "Mini",
    model: "Cooper S",
    generation: "F56",
    year: 2023,
    image: "https://images.unsplash.com/photo-1526069824293-406685e85766?auto=format&fit=crop&w=1200&q=80",
    rating: 8.6,
    ratings: 1248,
    driven: 2186,
    owners: 682,
    transmission: "Automatic",
    tags: ["Hot hatch", "Turbo", "Compact", "Fun"],
  },
  {
    id: "mini-cooper-jcw-f56",
    make: "Mini",
    model: "Cooper JCW",
    generation: "F56",
    year: 2023,
    image: "https://images.unsplash.com/photo-1526069824293-406685e85766?auto=format&fit=crop&w=1200&q=80",
    rating: 8.8,
    ratings: 936,
    driven: 1482,
    owners: 418,
    transmission: "Automatic",
    tags: ["Hot hatch", "John Cooper Works", "Turbo", "Performance"],
  },
  {
    id: "nissan-gtr-r35",
    make: "Nissan",
    model: "GT-R",
    generation: "R35",
    year: 2024,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    rating: 9.2,
    ratings: 2846,
    driven: 3918,
    owners: 826,
    transmission: "Automatic",
    tags: ["Twin-turbo", "All-wheel drive", "Supercar", "Japanese"],
  },
  {
    id: "nissan-350z-z33",
    make: "Nissan",
    model: "350Z",
    generation: "Z33",
    year: 2008,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    rating: 8.7,
    ratings: 2138,
    driven: 3482,
    owners: 1046,
    transmission: "Manual",
    tags: ["V6", "Rear-wheel drive", "Manual", "Japanese"],
  },
  {
    id: "nissan-370z-z34",
    make: "Nissan",
    model: "370Z",
    generation: "Z34",
    year: 2020,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    rating: 8.8,
    ratings: 1964,
    driven: 3068,
    owners: 918,
    transmission: "Manual",
    tags: ["V6", "Rear-wheel drive", "Manual", "Sports car"],
  },
  {
    id: "toyota-yaris-gr",
    make: "Toyota",
    model: "Yaris GR",
    generation: "XP210",
    year: 2024,
    image: "https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=80",
    rating: 9.1,
    ratings: 1846,
    driven: 2742,
    owners: 728,
    transmission: "Manual",
    tags: ["Hot hatch", "Turbo", "All-wheel drive", "Manual"],
  },
  {
    id: "toyota-supra-a90",
    make: "Toyota",
    model: "Supra",
    generation: "A90",
    year: 2024,
    image: "https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=80",
    rating: 9.0,
    ratings: 2634,
    driven: 3862,
    owners: 984,
    transmission: "Automatic",
    tags: ["Straight-6", "Turbo", "Rear-wheel drive", "Sports car"],
  },
  {
    id: "defender-90",
    make: "Land Rover",
    model: "Defender 90",
    generation: "L663",
    year: 2021,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    rating: 8.5,
    ratings: 491,
    driven: 760,
    owners: 206,
    transmission: "Automatic",
    tags: ["4x4", "Adventure", "Modern", "Utility"],
  },
  {
    id: "458-italia",
    make: "Ferrari",
    model: "458 Italia",
    generation: "F142",
    year: 2013,
    image: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80",
    rating: 9.5,
    ratings: 559,
    driven: 880,
    owners: 142,
    transmission: "Automatic",
    tags: ["V8", "Mid-engine", "Naturally aspirated", "Exotic"],
  },
  {
    id: "golf-gti-mk7",
    make: "Volkswagen",
    model: "Golf GTI",
    generation: "Mk7",
    year: 2017,
    image: "https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=1200&q=80",
    rating: 8.7,
    ratings: 1453,
    driven: 2310,
    owners: 516,
    transmission: "Manual",
    tags: ["Hot hatch", "Turbo", "Daily", "FWD"],
  },
  {
    id: "golf-r-mk7-5",
    make: "Volkswagen",
    model: "Golf R",
    generation: "Mk7.5",
    year: 2019,
    image: "https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=1200&q=80",
    rating: 9.0,
    ratings: 986,
    driven: 1640,
    owners: 382,
    transmission: "Automatic",
    tags: ["Hot hatch", "Turbo", "Daily", "AWD"],
  },
  ...audiModels.map((car, index): Car => ({
    ...car,
    make: "Audi",
    transmission: car.id === "s1-8x" ? "Manual" : "Automatic",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80",
    rating: Number((8.5 + ((index * 3) % 9) / 10).toFixed(1)),
    ratings: 340 + index * 83,
    driven: 520 + index * 115,
    owners: 114 + index * 31,
  })),
  ...ferrariModels.map((car, index): Car => ({
    ...car,
    make: "Ferrari",
    image: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80",
    rating: Number((8.8 + ((index * 2) % 8) / 10).toFixed(1)),
    ratings: 285 + index * 67,
    driven: 390 + index * 92,
    owners: 72 + index * 19,
  })),
  ...astonMartinModels.map((car, index): Car => ({
    ...car,
    make: "Aston Martin",
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
    rating: Number((8.7 + ((index * 2) % 7) / 10).toFixed(1)),
    ratings: 210 + index * 54,
    driven: 330 + index * 78,
    owners: 61 + index * 17,
  })),
  ...lamborghiniModels.map((car, index): Car => ({
    ...car,
    make: "Lamborghini",
    image: "https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&w=1200&q=80",
    rating: Number((8.8 + ((index * 2) % 7) / 10).toFixed(1)),
    ratings: 395 + index * 91,
    driven: 540 + index * 126,
    owners: 88 + index * 24,
  })),
  ...porscheModels.map((car, index): Car => ({
    ...car,
    make: "Porsche",
    image: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80",
    rating: Number((8.8 + ((index * 3) % 8) / 10).toFixed(1)),
    ratings: 470 + index * 116,
    driven: 720 + index * 158,
    owners: 126 + index * 37,
  })),
  ...mclarenModels.map((car, index): Car => ({
    ...car,
    make: "McLaren",
    image: mclarenEiffelImage,
    rating: Number((8.8 + ((index * 3) % 7) / 10).toFixed(1)),
    ratings: 275 + index * 78,
    driven: 410 + index * 104,
    owners: 69 + index * 21,
  })),
];
